name: Test Workflow

on:
  workflow_dispatch:

env:
  REPOSITORY: "bnw-template-container"

concurrency: test_workflow-${{ github.ref }}

jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_LIVE_CICD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LIVE_CICD_SECRET_ACCESS_KEY }}
          aws-region           : ${{ secrets.AWS_LIVE_CICD_REGION }}
      - name: Test Workflow
        run:  echo "This is a test."
